# Generated by Django 4.2.3 on 2023-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hightstedu',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
    ]
