# Generated by Django 4.2.3 on 2023-07-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_country_candidate_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='hightstedu',
            new_name='highestedu',
        ),
    ]
