# Generated by Django 4.2.3 on 2023-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_hightstedu_candidate_highestedu'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companydescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
    ]
