# Generated by Django 4.2.3 on 2023-08-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobdetails_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='app/img/jobpost'),
        ),
    ]
